---
### Generic smell configuration

detectors:
  # You can disable smells completely
  UtilityFunction:
    public_methods_only: true
  IrresponsibleModule:
    enabled: false
exclude_paths:
  - app/helpers
  - tmp
  - vendor
  - spec
  - config
  - bin
  - log
  - public
  - db
  - lib

